config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  resources :contacts
  resources :address_books do
    collection { post :import }
  end
  get 'home/index'
  root 'home#index'

end

app/models/address_book.rb
class AddressBook < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :name, length: {in: 4..30}

  has_and_belongs_to_many :contacts

  def to_csv
    contacts = self.contacts.all
    attributes = %w{first_name last_name eeid phone_number}.freeze
    CSV.generate(headers: true) do |csv|
      csv << attributes
      contacts.each do |contact|
        csv << contact.attributes.values_at(*attributes)
      end
    end
  end

  def self.import(file)
    # CSVWorker.perform_async(file)
    #
    # address_book = find_or_create_by!(name: "#{file.original_filename.chomp('.csv').strip}")
    # contact_ids = []
    #
    # CSV.foreach(file.path, headers: true) do |row|
    #   eeid = row['eeid']
    #   contact = Contact.create_with(eeid: eeid).find_or_create_by(row.to_hash)
    #   contact.update_columns!( first_name: contact.first_name, last_name: contact.last_name ) unless contact.new_record?
    #   contact_ids << contact.id
    # end
    #
    # return address_book.contact_ids = contact_ids
  end

  # def self.all_to_csv
  #   all.each do |address_book|
  #     address_book.to_csv
  #   end
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.update_or_create(attributes)
    assign_or_new(attributes).save
  end

  def self.assign_or_new(attributes)
    obj = first || new
    obj.assign_attributes(attributes)
    obj
    end


  def update_or_create(attributes)
    assign_or_new(attributes).save
  end

  def assign_or_new(attributes)
    obj = first || new
    obj.assign_attributes(attributes)
    obj
  end

end

app/models/contact.rb
class Contact < ApplicationRecord

  include PgSearch

  validates_presence_of :first_name, :last_name , :phone_number ,:eeid
  validates_uniqueness_of :phone_number, :eeid
  validates  :eeid , length: { is:11 }
  validates  :phone_number, length: { in: 8..13 }

  has_and_belongs_to_many :address_books

  pg_search_scope :search ,
                  against: [:first_name, :last_name],
                  using:  {
                      tsearch: { prefix: true, dictionary: "english"}
                  },
                  ignoring: :accents

end

app/controllers/address_books_controller.rb
class AddressBooksController < ApplicationController
  before_action :set_address_book, only: [:show, :edit, :update, :destroy]

  def index
    @address_books = AddressBook.order('updated_at DESC')
    respond_to do |format|
      format.html
      # format.csv { send_data  @address_books.all_to_csv }
    end

  end

  def show
    @contacts = @address_book.contacts
    respond_to do |format|
      format.html
      format.csv {send_data @address_book.to_csv, filename: "#{@address_book.name}.csv"}
    end
  end

  def new
    @address_book = AddressBook.new
  end

  def edit
  end

  def create
    @address_book = AddressBook.new(address_book_params)

    respond_to do |format|
      if @address_book.save
        format.html {redirect_to @address_book, notice: 'Address book was successfully created.'}
        format.json {render :show, status: :created, location: @address_book}
      else
        format.html {render :new}
        format.json {render json: @address_book.errors, status: :unprocessable_entity}
      end
    end
  end

  def import
    if params[:file].present?
      csv_file = params[:file]
      CSVImportWroker.perform_async(csv_file.path, csv_file.original_filename)
      redirect_to address_books_path, notice: "Successfully uploaded file #{csv_file.original_filename.chomp('.csv').strip}"
    else
      redirect_to address_books_path, notice: 'Nothing imported...'
    end

  end


  def update
    respond_to do |format|
      if @address_book.update(address_book_params)
        format.html {redirect_to @address_book, notice: 'Address book was successfully updated.'}
        format.json {render :show, status: :ok, location: @address_book}
      else
        format.html {render :edit}
        format.json {render json: @address_book.errors, status: :unprocessable_entity}
      end
    end
  end


  def destroy
    @address_book.destroy
    respond_to do |format|
      format.html {redirect_to address_books_url, notice: 'Address book was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  def set_address_book
    @address_book = AddressBook.find(params[:id])
  end

  def address_book_params
    params.require(:address_book).permit(:name, :contact_ids => [])
  end

  def csv_file_param
    # params.require
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].blank?
      @contacts = Contact.order('first_name ASC').paginate(:page => params[:page], :per_page => 30)
    else
      @contacts = Contact.search( params[:search]).paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @groups = @contact.address_books
  end


  def new
    @contact = Contact.new
  end


  def edit
  end


  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number, :eeid, address_book_ids: [])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/address_books_helper.rb
module AddressBooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active(controller)
    params[:controller] == controller ? "active" : nil
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/address_books/_form.html.erb
<%= simple_form_for(@address_book) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
    <!--<div class="from-group">-->
      <!--<%= f.association :contacts, label_method: :first_name, value_method: :id  %>-->
    <!--</div>-->

  <div class="form-actions">
    <%= f.button :submit, input_html:{class:'btn btn-success'}%>
  </div>
<% end %>

app/views/address_books/_import.html.erb
<div class="form">

</div>

app/views/address_books/edit.html.erb
<div class="row">
  <div class="col">
    <h1>Editing Address Book</h1>

    <%= render 'form', address_book: @address_book %>

    <%= link_to 'Show', @address_book %> |
    <%= link_to 'Back', address_books_path %>
  </div>
</div>

app/views/address_books/index.html.erb
<div class="row">
  <div class="col">
    <p id="notice" class="alert-success"><%= notice %></p>

    <h1 class="text-center well">Address Books</h1>
    <hr>

    <%= link_to 'New Address Book', new_address_book_path, class: 'btn btn-info float-left' %>

    <%= link_to 'Impor Address Book', '#', class: 'btn btn-primary float-right', data:{ toggle: 'modal', target: '#importModal' }  %>



    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <th>Name</th>
        <!--<th colspan="3"></th>-->
      </tr>
      </thead>
      <tbody>
      <% @address_books.each do |address_book| %>
          <tr>
            <td>  <%= address_book.name %></td>
            <td><%= link_to 'Show', address_book %></td>
            <td> <%= link_to 'Download', address_book_path(address_book, format: 'csv') %> </td>
            <td><%= link_to 'Destroy', address_book, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %></td>
            <!--<td><%= link_to 'Edit', edit_address_book_path(address_book) %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Import Address Book</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag import_address_books_path, multipart: true do %>
            <%= file_field_tag :file, class: 'form-control float-left', accept: 'text/csv' %>
            <%= submit_tag "Import", class: 'btn btn-success float-right' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/address_books/new.html.erb
<h1>New Address Book</h1>

<%= render 'form', address_book: @address_book %>

<%= link_to 'Back', address_books_path %>

app/views/address_books/show.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>
    <div class="card text-center">
      <div class="card-header">
        <h2><%= @address_book.name %></h2>
        <%= link_to 'Back', address_books_path, class: 'btn btn-secondary float-left' %>
        <%= link_to 'Delete', @address_book,method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-right' %>
        <%= link_to 'Edit', edit_address_book_path(@address_book), class: 'btn btn-info float-right' %>

      </div>
      <div class="card-body">
        <!--<h4 class="card-title"><%= @address_book.name %></h4>-->
        <p class="card-text">List of contacts in this address book.</p>
      </div>

      <ul class="list-group list-group-flush">
        <% @contacts.each do |contact| %>
            <li class="list-group-item"> <strong> <%= contact.first_name %> - <%= contact.last_name %> </strong>  <%= link_to '->', contact_url(contact) %> </li>
        <% end %>
      </ul>

      <div class="card-footer text-muted">
        <%= @address_book.name %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone_number %>
    <%= f.input :eeid, label: 'Estonian ID' %>
  </div>

    <div class="form-inputs">
      <span class="input-group-addon">
      <%= f.association :address_books, as: :check_boxes, label_method: :name, value_method: :id %>
      </span>
    </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>
    <h1 class="text-center">Contacts</h1>
  </div>
  <hr>
</div>
<div class="row">
  <div class="col-6">
    <%= form_tag contacts_path, method: :get, controller: :contacts, action: :index, class: 'form-inline' do %>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'search for contact...' %>
        <%= submit_tag 'Find', name: nil, class: 'btn btn-success' %>
    <% end %>
  </div>
  <div class="col-6">
    <%= link_to 'New Contact', new_contact_path, class: 'btn btn-block btn-success' %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-striped table-striped">
      <thead class="thead-inverse">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <!--<th>Phone number</th>-->
        <!--<th>Eeid</th>-->
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.first_name %></td>
            <td><%= contact.last_name %></td>
            <!--<td><%= contact.phone_number %></td>-->
            <!--<td><%= contact.eeid %></td>-->
            <td><%= button_to 'Show', contact, method: :get, class: 'btn btn-info' %></td>
            <!--<td><%= button_to 'Edit', edit_contact_path(contact), method: :get, class: 'btn btn-success' %></td>-->
            <!--<td><%= button_to 'Destroy', contact, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @contacts %>
  </div>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col">
    <p id="notice"><%= notice %></p>

    <div class="card mb-3">
      <div class="card-header">
        <%= @contact.first_name %>  <%= @contact.last_name %>
      </div>
      <br>
      <%= image_tag 'user-icon', size: '300x300', class: 'card-img-top' %>
      <!--<img class="card-img-top" src="..." alt="Card image cap">-->
      <div class="card-body">
        <h4 class="card-title"> <strong>Name: </strong> <%= @contact.first_name %>  <%= @contact.last_name %></h4>
        <p class="card-text">
          <strong>Phone number:</strong>
          <%= @contact.phone_number %>
        </p>

        <p class="card-text">
          <strong>Estonian ID:</strong>
          <%= @contact.eeid %>
        </p>

        <p class="card-text">
          <strong>Address Books: </strong>  <%= @groups.pluck(:name).join(', ')  %>
        </p>

        <!--<button type="button" class="btn btn-primary btn-lg">Large button</button>-->
        <!--<button type="button" class="btn btn-secondary btn-lg">Large button</button>-->

        <%= button_to 'Back', contacts_path, method: :get, class: 'btn btn-lg btn-outline-secondary btn-block' %>
        <%= button_to 'Edit', edit_contact_path(@contact), method: :get, class: 'btn btn-outline-primary btn-lg btn-block' %>
        <%= button_to 'Destroy', @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-lg btn-block' %>

      </div>
      <div class="card-footer text-muted">
        <p class="card-text"><small class="text-muted"> Updated <%=  time_ago_in_words @contact.updated_at  %></small></p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <%= link_to 'Contacts', contacts_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Address Books', address_books_path, class: 'btn btn-info btn-lg' %>
  </p>
</div>

app/views/layouts/_navs.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <%= link_to "Tik'vaa", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%=is_active('contacts')%> ">
        <%= link_to 'Contacts', contacts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%=is_active('address_books')%>">
        <%= link_to 'Address Books', address_books_path, class: 'nav-link' %>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <%= form_tag contacts_path, method: :get, controller: :contacts, action: :index do %>
          <%=  text_field_tag :search, params[:search], class: 'form-control mr-sm-2', placeholder: 'search for contact...' %>
          <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-success my-2 my-sm-0'  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Address Book App</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% unless current_page? root_path  %>
    <%= render 'layouts/navs' %>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>